version: '3.9'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
  laravel:
    image: almightykira/quis-cloud-native-monolith:latest
    environment:
      - APP_URL=""
volumes:
  db_data: