version: '3.9'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  phpmyadmin:
    image: phpmyadmin
    profiles: [ "debug" ]
    ports:
      - 33306:80
    environment:
      - MYSQL_ROOT_PASSWORD
      - PMA_HOST=mysql
    depends_on:
      - mysql
  laramix:
    image: node:14.15-alpine3.13
    command: [ ".docker/laramix-entrypoint" ]
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
    profiles: [ "dev" ]
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      target: php_laravel
    ports:
      - 8000:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./:/var/www/php
    depends_on:
      - mysql