version: '3.9'
services:
  mysql:
    image: 192.168.100.250:8086/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secretRootPasswd
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
  laravel:
    image: 192.168.100.250:8086/almightykira/quis-cloud-native-monolith:latest
    ports:
      - "80:80"
    environment:
      - APP_URL=""
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=error
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    depends_on:
      - mysql
volumes:
  mysql_data: